import numpy as np
import matplotlib.pyplot as plt

ctp_raw = np.array([2,3,4,5,6])

cp_p1 = np.load('cp_p1.npy')
CP_p1_Cor = np.load('CP_p1_Cor.npy')
cp_p2 = np.load('cp_p2.npy')
CP_p2_Cor = np.load('CP_p2_Cor.npy')
cp_p3 = np.load('cp_p3.npy')
CP_p3_Cor = np.load('CP_p3_Cor.npy')
cp_p05 = np.load('cp_p05.npy')

ct_p1 = np.load('ct_p1.npy')
CT_p1_Cor = np.load('CT_p1_Cor.npy')
ct_p2 = np.load('ct_p2.npy')
CT_p2_Cor = np.load('CT_p2_Cor.npy')
ct_p3 = np.load('ct_p3.npy')
CT_p3_Cor = np.load('CT_p3_Cor.npy')
ct_p05 = np.load('ct_p05.npy')

ctp_sol_p1 = np.load('CTP_sol_p1.npy')
ctp_sol_p2 = np.load('CTP_sol_p2.npy')
ctp_sol_p3 = np.load('CTP_sol_p3.npy')

plt.figure(figsize=(10, 5))
plt.plot(ctp_raw, cp_p1, 'o-', label = 'Beta = 0.1 LES', color = 'blue')
plt.plot(ctp_raw, cp_p05, 'o-', label = 'Beta = 0.005 LES', color = 'black')
plt.plot(ctp_sol_p1, CP_p1_Cor, '^:', label = 'Corrected from Beta = 0.1', color = 'red')
plt.xlabel('CT Prime')
plt.ylabel('CP')
plt.title('Blockage Correction from Beta = 0.1 LES Data')
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
plt.savefig('CP_P1.png', bbox_inches='tight')

plt.figure(figsize=(10, 5))
plt.plot(ctp_raw, ct_p1, 'o-', label = 'Beta = 0.1 LES', color = 'blue')
plt.plot(ctp_raw, ct_p05, 'o-', label = 'Beta = 0.005 LES', color = 'black')
plt.plot(ctp_sol_p1, CT_p1_Cor, '^:', label = 'Corrected from Beta = 0.1', color = 'red')
plt.xlabel('CT Prime')
plt.ylabel('CT')
plt.title('Blockage Correction from Beta = 0.1 LES Data')
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
plt.savefig('CT_P1.png', bbox_inches='tight')

plt.figure(figsize=(10, 5))
plt.plot(ctp_raw, cp_p2, 'o-', label = 'Beta = 0.2 LES', color = 'blue')
plt.plot(ctp_raw, cp_p05, 'o-', label = 'Beta = 0.005 LES', color = 'black')
plt.plot(ctp_sol_p2, CP_p2_Cor, '^:', label = 'Corrected from Beta = 0.2', color = 'red')
plt.xlabel('CT Prime')
plt.ylabel('CP')
plt.title('Blockage Correction from Beta = 0.2 LES Data')
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
plt.savefig('CP_P2.png', bbox_inches='tight')

plt.figure(figsize=(10, 5))
plt.plot(ctp_raw, ct_p2, 'o-', label = 'Beta = 0.2 LES', color = 'blue')
plt.plot(ctp_raw, ct_p05, 'o-', label = 'Beta = 0.005 LES', color = 'black')
plt.plot(ctp_sol_p2, CT_p2_Cor, '^:', label = 'Corrected from Beta = 0.2', color = 'red')
plt.xlabel('CT Prime')
plt.ylabel('CT')
plt.title('Blockage Correction from Beta = 0.2 LES Data')
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
plt.savefig('CT_P2.png', bbox_inches='tight')

plt.figure(figsize=(10, 5))
plt.plot(ctp_raw, cp_p3, 'o-', label = 'Beta = 0.3 LES', color = 'blue')
plt.plot(ctp_raw, cp_p05, 'o-', label = 'Beta = 0.005 LES', color = 'black')
plt.plot(ctp_sol_p3, CP_p3_Cor, '^:', label = 'Corrected from Beta = 0.3', color = 'red')
plt.xlabel('CT Prime')
plt.ylabel('CP')
plt.title('Blockage Correction from Beta = 0.3 LES Data')
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
plt.savefig('CP_P3.png', bbox_inches='tight')

plt.figure(figsize=(10, 5))
plt.plot(ctp_raw, ct_p3, 'o-', label = 'Beta = 0.3 LES', color = 'blue')
plt.plot(ctp_raw, ct_p05, 'o-', label = 'Beta = 0.005 LES', color = 'black')
plt.plot(ctp_sol_p3, CT_p3_Cor, '^:', label = 'Corrected from Beta = 0.3', color = 'red')
plt.xlabel('CT Prime')
plt.ylabel('CT')
plt.title('Blockage Correction from Beta = 0.3 LES Data')
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
plt.savefig('CT_P3.png', bbox_inches='tight')