import numpy as np
import matplotlib.pyplot as plt

C_CP_RP = np.load('C_CP_RP.npy')
C_CTP_Sol = np.load('C_CTP_Sol.npy')
CP_Cor_BW_RP = np.load('CP_Cor_BW_RP.npy')
CP_Cor_Houl_RP = np.load('CP_Cor_Houl_RP.npy')
CP_Cor_Mask_RP = np.load('CP_Cor_Mask_RP.npy')
CP_Cor_MS_RP = np.load('CP_Cor_MS_RP.npy')
CP_Cor_Wer_RP = np.load('CP_Cor_Wer_RP.npy')
CP_RP_Cor = np.load('CP_RP_Cor.npy')
U_CP_RP = np.load('U_CP_RP.npy')
U_CTP_Sol = np.load('U_CTP_Sol_RP.npy')

C_CT_RP = np.load('C_CT_RP.npy')
CT_Cor_RP = np.load('CT_RP_Cor.npy')
U_CT_RP = np.load('U_CT_RP.npy')

CT_Cor_BW_RP = np.load('CT_Cor_BW_RP.npy')
CT_Cor_Houl_RP = np.load('CT_Cor_Houl_RP.npy')
CT_Cor_Mask_RP = np.load('CT_Cor_Mask_RP.npy')
CT_Cor_MS_RP = np.load('CT_Cor_MS_RP.npy')
CT_Cor_Wer_RP = np.load('CT_Cor_Wer_RP.npy')

plt.figure(figsize=(10, 6))
plt.plot(C_CTP_Sol, C_CP_RP, label='Beta = 0.35 Data', color = 'blue', marker='o', linestyle='-')
plt.plot(U_CTP_Sol, U_CP_RP, label = 'Beta = 0.005 Data', color = 'black', marker = 'o', linestyle = '-')
plt.plot(C_CTP_Sol,CP_RP_Cor, label= 'Yaw Model Correction', color = 'red', marker='^', linestyle=':')
plt.plot(C_CTP_Sol, CP_Cor_BW_RP, label='Barnsley/Wellicome Correction', color = 'orange', marker = '^', linestyle = ':')
plt.plot(C_CTP_Sol, CP_Cor_Houl_RP, label = 'Houlsby Correction', color = 'yellow', marker = '^', linestyle = ':')
plt.plot(C_CTP_Sol, CP_Cor_Mask_RP, label = 'Maskell Correction', color = 'green', marker = '^', linestyle = ':')
plt.plot(C_CTP_Sol, CP_Cor_MS_RP, label = 'Mikkelsen/Sorensen Correction (Unverified)', color = 'purple', marker = '^', linestyle = ':')
plt.plot(C_CTP_Sol, CP_Cor_Wer_RP, label = 'Werle Correction', color = 'brown', marker = '^', linestyle = ':')
plt.xlabel('C_T Prime')
plt.ylabel('C_P')
plt.title('Blockage Correction Comparison for Beta = 0.35 to Beta = 0.005 using Experimental Data')
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
plt.grid()
plt.savefig('yawtheory_ascorrect_plot.png', bbox_inches='tight', dpi=300)

plt.figure(figsize=(10, 6))
plt.plot(C_CTP_Sol, CT_Cor_RP, '^', linestyle = ':', label='Yaw Model Correction', color = 'red')
plt.plot(C_CTP_Sol, C_CT_RP, 'o-', label='Beta = 0.35 Data', color = 'blue')
plt.plot(U_CTP_Sol, U_CT_RP, 'o-', label = 'Beta = 0.005 Data', color = 'black')
plt.plot(C_CTP_Sol, CT_Cor_BW_RP, '^', linestyle = ':', label='Barnsley/Wellicome Correction', color = 'orange')
plt.plot(C_CTP_Sol, CT_Cor_Houl_RP, '^', linestyle = ':', label = 'Houlsby Correction', color = 'yellow')
plt.plot(C_CTP_Sol, CT_Cor_Mask_RP, '^', linestyle = ':', label = 'Maskell Correction', color = 'green')
plt.plot(C_CTP_Sol, CT_Cor_MS_RP, '^', linestyle = ':', label = 'Mikkelsen/Sorensen Correction (Unverified)', color = 'purple')
plt.plot(C_CTP_Sol, CT_Cor_Wer_RP, '^', linestyle = ':', label = 'Werle Correction', color = 'brown')
plt.xlabel('CT Prime')
plt.ylabel('CT')
plt.title('Blockage Correction Comparison for Beta = 0.35 to Beta = 0.005 using Experimental Data')
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
plt.grid()
plt.savefig('yawtheory_ascorrect_CT_plot.png', bbox_inches='tight', dpi=300)